### ISSUE TITLE
which repo?

### ISSUE THREAD

**Issue by neutmute** [KennethB/Chocolatey_VisualStudio2015#2]
Hi @KennethB - which is the correct repo for the chocolatey package `visualstudio2015enterprise`

There is this repo and also https://github.com/KennethB/Chocolatey-Packages  - i suspect the latter but I can't raise issues against it? 
I can do a straight PR but I prefer to raise an issue first to discuss my proposed change.

fyi the change is to be able to specify a local path to the ISO to speed up the test cycle of installing/reduce bandwidth for multiple boxes being spun up with boxstarter

**Comment by neutmute** [comment]
See https://github.com/neutmute/nm-chocolatey-packs/blob/master/sqlserver2016/tools/chocolateyinstall.ps1#L118 for an example of how I would mount a local ISO and execute setup.

The local iso would be optional of course and the fallback would be current behaviour of downloading from MS

**Comment by KennethB** [comment]
I've got issues turned on the other repo now.

I'll take a look at this when I get a chance or if you want to push the change to make it happen faster I'll test it and update the package.

I think this would help some users that have been having problems with timeout issues.

**Comment by neutmute** [comment]
awesome - thanks
